name: Find JustSportHD Domain

on:
  workflow_dispatch:  # Elle tetikleme
  schedule:
    - cron: '0 12 * * *'  # Otomatik tetikleme (opsiyonel)

jobs:
  domain_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run domain checker
        id: run_domain_checker
        env:
          AUTO_DOMAIN_CHECK: 1
        run: python find_domain.py

      - name: Upload working_domain.txt if domain found
        if: env.DOMAIN_FOUND == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: working-domain
          path: working_domain.txt
